# Generated by Django 2.0.4 on 2019-07-09 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0002_auto_20190709_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesprofile',
            name='employee_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
