# Generated by Django 2.0.4 on 2019-07-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0004_auto_20190719_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesconfiguration',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='monitoringTool.Devices'),
        ),
    ]
