# Generated by Django 2.0.4 on 2019-07-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0007_auto_20190719_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesconfiguration',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='monitoringTool.Devices'),
        ),
        migrations.AlterField(
            model_name='devicesconfiguration',
            name='device_config_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
