# Generated by Django 2.0.4 on 2019-07-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0008_auto_20190719_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='cluster_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activeClustersAndDevices', related_query_name='activeClusterAndDevice', to='monitoringTool.ClustersSetup'),
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='content_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activeClustersAndDevices', related_query_name='activeClusterAndDevice', to='monitoringTool.ContentsSetup'),
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activeClustersAndDevices', related_query_name='activeClusterAndDevice', to='monitoringTool.Devices'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', related_query_name='area', to='monitoringTool.Cities'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', related_query_name='city', to='monitoringTool.Countries'),
        ),
        migrations.AlterField(
            model_name='clustersnetworkconfiguration',
            name='cluster_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clustersNetworkConfigurations', related_query_name='clustersNetworkConfiguration', to='monitoringTool.ClustersSetup'),
        ),
        migrations.AlterField(
            model_name='clusterssetup',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusterSetups', related_query_name='clusterSetup', to='monitoringTool.Areas'),
        ),
        migrations.AlterField(
            model_name='clusterssetup',
            name='cluster_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clusterSetups', related_query_name='clusterSetup', to='monitoringTool.ClusterTypes'),
        ),
        migrations.AlterField(
            model_name='clustersweathercondition',
            name='cluster_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clustersWeatherConditions', related_query_name='clustersWeatherCondition', to='monitoringTool.ClustersSetup'),
        ),
        migrations.AlterField(
            model_name='contentcontracts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contentContracts', related_query_name='contentContract', to='monitoringTool.ClientsProfile'),
        ),
        migrations.AlterField(
            model_name='contentcontracts',
            name='content_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contentContracts', related_query_name='contentContract', to='monitoringTool.ContentsSetup'),
        ),
        migrations.AlterField(
            model_name='contentcontracts',
            name='our_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentContracts', related_query_name='contentContract', to='monitoringTool.EmployeesProfile'),
        ),
        migrations.AlterField(
            model_name='contentsdata',
            name='content_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contentsData', related_query_name='contentData', to='monitoringTool.ContentsSetup'),
        ),
        migrations.AlterField(
            model_name='contentssetup',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contentsSetup', related_query_name='contentSetup', to='monitoringTool.ContentTypes'),
        ),
        migrations.AlterField(
            model_name='devicesconfiguration',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deviceConfigurations', related_query_name='deviceConfiguration', to='monitoringTool.Devices'),
        ),
        migrations.AlterField(
            model_name='stafflogin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffLogins', related_query_name='staffLogin', to='monitoringTool.EmployeesProfile'),
        ),
    ]
