# Generated by Django 2.0.4 on 2019-07-21 02:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0009_auto_20190720_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentsSetupDataContract',
            fields=[
                ('content_setup_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_title', models.CharField(max_length=128)),
                ('is_content_new', models.CharField(max_length=4)),
                ('content_data', models.FileField(upload_to='contentsData/', verbose_name='')),
                ('content_contract_data', models.FileField(max_length=128, upload_to='')),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=13)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_modified_user', models.CharField(max_length=80)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ContentsSetupDataContract', related_query_name='ContentSetupDataContract', to='monitoringTool.ClientsProfile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ContentsSetupDataContract', related_query_name='ContentSetupDataContract', to='monitoringTool.ContentTypes')),
                ('our_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ContentsSetupDataContract', related_query_name='ContentSetupDataContract', to='monitoringTool.EmployeesProfile')),
            ],
            options={
                'verbose_name_plural': 'ContentsSetupDataContract',
            },
        ),
        migrations.RemoveField(
            model_name='contentcontracts',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contentcontracts',
            name='content_setup',
        ),
        migrations.RemoveField(
            model_name='contentcontracts',
            name='our_representative',
        ),
        migrations.RemoveField(
            model_name='contentsdata',
            name='content_setup',
        ),
        migrations.RemoveField(
            model_name='contentssetup',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='content_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activeClustersAndDevices', related_query_name='activeClusterAndDevice', to='monitoringTool.ContentsSetupDataContract'),
        ),
        migrations.DeleteModel(
            name='ContentContracts',
        ),
        migrations.DeleteModel(
            name='ContentsData',
        ),
        migrations.DeleteModel(
            name='ContentsSetup',
        ),
    ]
