# Generated by Django 2.0.4 on 2019-07-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0010_auto_20190721_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('change_request_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('change_request_title', models.CharField(max_length=64)),
                ('change_request_message', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='cluster_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndDevices', related_query_name='activeClusterAndDevice', to='monitoringTool.ClustersSetup'),
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='content_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndDevices', related_query_name='activeClusterAndDevice', to='monitoringTool.ContentsSetupDataContract'),
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndDevices', related_query_name='ActiveClusterAndDevice', to='monitoringTool.Devices'),
        ),
        migrations.AlterField(
            model_name='contentssetupdatacontract',
            name='content_contract_data',
            field=models.FileField(upload_to='contractFile/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='content_data',
            field=models.FileField(null=True, upload_to='contentsDataTest/', verbose_name=''),
        ),
    ]
