# Generated by Django 2.0.4 on 2019-07-23 23:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0011_auto_20190723_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClustersAndContents',
            fields=[
                ('active_cluster_and_content_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_modified_user', models.CharField(max_length=80)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('cluster_setup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndContents', related_query_name='activeClusterAndContent', to='monitoringTool.ClustersSetup')),
                ('content_setup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndContents', related_query_name='activeClusterAndContent', to='monitoringTool.ContentsSetupDataContract')),
            ],
            options={
                'verbose_name_plural': 'ActiveClustersAndContents',
            },
        ),
        migrations.RemoveField(
            model_name='activeclustersanddevices',
            name='content_setup',
        ),
    ]
