# Generated by Django 2.0.4 on 2019-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0012_auto_20190724_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesconfiguration',
            name='extra_info',
            field=models.CharField(max_length=514),
        ),
    ]
