# Generated by Django 2.1.11 on 2019-09-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringTool', '0013_auto_20190725_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclustersandcontents',
            name='cluster_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndContents', related_query_name='ActiveClusterAndContent', to='monitoringTool.ClustersSetup'),
        ),
        migrations.AlterField(
            model_name='activeclustersanddevices',
            name='cluster_setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActiveClustersAndDevices', related_query_name='ActiveClusterAndDevice', to='monitoringTool.ClustersSetup'),
        ),
    ]
